# More option see https://github.com/DreamMaoMao/mango/wiki/

source=~/.config/mango/config/window-effect.conf
source=~/.config/mango/config/animation.conf
source=~/.config/mango/config/layout.conf
source=~/.config/mango/config/misc.conf
source=~/.config/mango/config/inputs.conf
source=~/.config/mango/config/outputs.conf
source=~/.config/mango/config/envvars.conf
source=~/.config/mango/config/appearance.conf
source=~/.config/mango/config/binds.conf
source=~/.config/mango/config/rules.conf
source-optional=~/.config/config/colors.conf




