[pyprland]
plugins = ["expose", "scratchpads", "toggle_special", "shift_monitors"]

# using variables for demonstration purposes (not needed)
[pyprland.variables]
term_classed = "kitty --class"

[scratchpads.terminal]
animation = "fromTop"
command = "[term_classed] main-dropterm"
class = "main-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
lazy = true

[scratchpads.yazi]
animation = "fromTop"
max_size = "1920px 100%"
command = "[term_classed] main-dropyazi fish -c yazi"
class = "main-dropyazi"
size = "75% 60%"
unfocus = "hide"
hysteresis = 0.1
# means 10% margin tolerance. For example, if the scratchpad is nearly hidden
# and you bump focus/move it slightly, Pyprland won’t immediately toggle it —
# it waits until the change passes that threshold.
lazy = true

[scratchpads.btop]
animation = "fromTop"
command = "[term_classed] main-dropbtop btop"
class = "main-dropbtop"
max_size = "1920px 100%"
size = "80% 70%"
lazy = true
close_on_hide = true

[scratchpads.nvtop]
animation = "fromTop"
command = "[term_classed] main-dropnvtop nvtop"
class = "main-dropnvtop"
max_size = "1920px 100%"
size = "80% 70%"
lazy = true
close_on_hide = true
