[AdditionalOptions]
extensions            = keyboardShortcut.js
custom_apps           = 
sidebar_config        = 0
home_config           = 1
experimental_features = 0

[Patch]

[Setting]
overwrite_assets       = 1
spotify_launch_flags   = --remote-debugging-port=9222
inject_css             = 1
check_spicetify_update = 0
always_enable_devtools = 1
spotify_path           = $HOME/.nix-profile/share/spotify/
prefs_path             = $HOME/.config/spotify/prefs
color_scheme           = matugen
current_theme          = Sleek
inject_theme_js        = 1
replace_colors         = 1

[Preprocesses]
disable_ui_logging = 1
remove_rtl_rule    = 1
expose_apis        = 1
disable_sentry     = 1

; DO NOT CHANGE!
[Backup]
version = 1.2.90.451.gb094aab0
with    = 2.43.2
