unqualified-search-registries = ["docker.io"]

# Docker Hub mirrors
[[registry]]
prefix = "docker.io"
location = "docker.io"

[[registry.mirror]]
location = "docker.arvancloud.ir"
insecure = true

[[registry.mirror]]
location = "docker.mobinhost.com"
insecure = true

[[registry.mirror]]
location = "docker.devneeds.ir"
insecure = true

# GitHub Container Registry mirror
[[registry]]
prefix = "ghcr.io"
location = "ghcr.io"

[[registry.mirror]]
location = "ghcr-mirror.liara.ir"
insecure = true
